language: node_js
node_js: 11.10.1
branchs:
  only:
    - master
cache:
  directories:
    - node_modules
before_script:
  - yarn global add gitbook-cli
script:
  - gitbook build
deploy:
  provider: page
  skip_cleanup: true
  github_token: $GITHUB_BLOG
  keep_history: true
  on:
    branch: master
  local_dir: _book
