language: node_js
node_js: 11.10.1
sudo: required
branchs:
  only:
    - master
env:
  global:
    - GH_REF: github.com/codeshareman/m-blog.git
cache:
  directories:
    - node_modules
before_script:
  - yarn global add gitbook-cli
addons:
  ssh_known_hosts: 49.235.1.23
before_install:
  - openssl aes-256-cbc -K $encrypted_04674a2f3de9_key -iv $encrypted_04674a2f3de9_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
script:
  - gitbook build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_BLOG
  keep_history: true
  on:
    branch: master
after_script:
  - ssh travis@49.235.1.23 -o StrictHostKeyChecking=no 'cd /usr/share/nginx/html/m-blog && git pull && git checkout travis-build'
