language: node_js
node_js: 11.10.1
branchs:
  only:
  - master
cache:
  directories:
  - node_modules
before_script:
- yarn global add gitbook-cli
script:
- gitbook build
addons:
  ssh_known_hosts: 49.235.1.23  
before_install:
- openssl aes-256-cbc -K $encrypted_04674a2f3de9_key -iv $encrypted_04674a2f3de9_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
after_success:
- ssh travis@49.235.1.23 -o StrictHostKeyChecking=no 'cd ~/travis/m-blog && git pull && gitbook build'
